### ISSUE TITLE
Older releases download links incorrect

### ISSUE THREAD

**Issue by dkav** [Circuitscape/www.circuitscape.org#18]
Links to Windows and Mac binaries are incorrect. Website - https://circuitscapebinaries.blob.core.windows.net - does not exist.

See https://github.com/Circuitscape/www.circuitscape.org/blob/master/downloads/index.md

**Comment by dkav** [comment]
@ViralBShah can you get someone to fix this.

**Comment by ranjanan** [comment]
Let me check

**Comment by ranjanan** [comment]
I think all our binaries are below a 100 MB (except for the short lived v5 GUI, which we can scrap). I'll get them uploaded to Github.

**Comment by dkav** [comment]
Still not fixed.

**Comment by ranjanan** [comment]
Sorry about the delay on this. All links are updated now.
